export interface BlogArticle {
  id: string;
  title: string;
  category: string;
  image: string;
  createdAt: string;
  readTime: string;
  tags: string[];
  excerpt: string;
  body: string[];
  officialLinks?: OfficialLink[];
}

export interface OfficialLink {
  title: string;
  url: string;
  purpose: string;
}

export const BLOG_ARTICLES: BlogArticle[] = [
  {
    id: "category-dmv",
    title: "DMV Checklist for New California Residents",
    category: "DMV",
    image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=1200&q=80",
    createdAt: "July 2, 2026",
    readTime: "6 min read",
    tags: ["DMV", "Driver License", "REAL ID", "California"],
    excerpt: "Plan the DMV tasks most newcomers handle first, from license timing to REAL ID documents.",
    body: [
      "Start by deciding which DMV task you need first: a California driver's license, state ID, REAL ID, vehicle registration, or address update. New residents should review official DMV timelines because deadlines can depend on when they establish residency and whether they bring a vehicle from another state.",
      "Prepare identity, residency, and legal-presence documents before booking an appointment. Common documents include a passport or other identity proof, proof of California address, Social Security information when applicable, and any existing out-of-state license or registration.",
      "Use the DMV website to check forms, fees, test requirements, and appointment availability before visiting an office. Many steps can start online, but users should confirm current rules on the official DMV site before relying on any checklist.",
      "After the visit, keep receipts, temporary paperwork, test results, and renewal reminders together. If a REAL ID or license card arrives by mail, verify the name and address as soon as it is delivered.",
    ],
  },
  {
    id: "category-banking",
    title: "新移民如何开美国银行账户",
    category: "Banking",
    image: "https://images.unsplash.com/photo-1565514158740-064f34bd6cfd?auto=format&fit=crop&w=1200&q=80",
    createdAt: "July 4, 2026",
    readTime: "8 min read",
    tags: ["美国银行", "银行开户", "支票账户", "储蓄账户", "新移民"],
    excerpt: "帮助新移民选择合适的银行和账户，并准备开户身份材料、地址信息及初始存款。",
    body: [
      "适合人群：刚到美国还没有美国银行账户的人、需要接收工资或支付房租的人、不熟悉美国银行费用和账户规则的人，以及想比较银行与信用合作社的新居民。",
      "准备清单：护照或其他政府签发照片证件、第二份身份证明、SSN 或 ITIN、美国居住或邮寄地址、美国电话号码、电子邮箱、初始存款、工作学校或移民文件、英文姓名格式和需要询问银行的问题清单。",
      "先选择金融机构。可以比较传统银行、网上银行和信用合作社，重点看分行和 ATM 是否方便、手机银行是否好用、是否提供语言服务，以及日常转账和国际汇款是否适合自己。",
      "选择账户类型时，日常消费和收工资通常使用 checking account；存放备用资金可以考虑 savings account。开户前询问月费、最低余额、ATM 费、透支费、国际汇款费、支票费和关闭账户条件。",
      "确认存款保障。银行账户应确认是否受到 FDIC 保险保障；信用合作社则确认是否受到相应的联邦存款保障。不要只比较开户奖励，也要查看长期费用和账户限制。",
      "新移民材料较复杂时，前往分行通常更容易确认文件是否被接受。银行通常需要政府签发身份证件，并可能要求 SSN、ITIN 或其他身份识别信息；不同机构的文件政策可能不同。",
      "开户后设置强密码、双重验证、交易提醒和银行卡锁定功能。保存开户协议、费用表、routing number、account number 和银行联系方式，但不要把账号信息发给不可信的人。",
      "官方提醒：银行必须核验客户身份，但每家银行接受的文件和开户政策不同。开户前直接联系银行，并索取正式费用表和账户协议。不要通过社交媒体上的开户代理提交护照或银行信息。",
    ],
    officialLinks: [
      {
        title: "FDIC GetBanked",
        url: "https://www.fdic.gov/getbanked",
        purpose: "了解开户准备、低费用账户和非美国公民开户信息。",
      },
      {
        title: "FDIC BankFind Suite",
        url: "https://banks.data.fdic.gov/bankfind-suite/bankfind",
        purpose: "核实一家银行是否属于 FDIC-insured bank。",
      },
      {
        title: "FDIC Deposit Insurance",
        url: "https://www.fdic.gov/resources/deposit-insurance",
        purpose: "了解哪些存款受到 FDIC 保障以及保障的基本规则。",
      },
      {
        title: "Consumer Financial Protection Bureau — Bank Accounts",
        url: "https://www.consumerfinance.gov/consumer-tools/bank-accounts/",
        purpose: "了解银行账户、费用、开户被拒及消费者权利。",
      },
      {
        title: "CFPB — Submit a Complaint",
        url: "https://www.consumerfinance.gov/complaint/",
        purpose: "遇到银行账户或金融服务问题时提交消费者投诉。",
      },
    ],
  },
  {
    id: "category-housing",
    title: "第一次在加州租房完整 checklist",
    category: "Housing",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1200&q=80",
    createdAt: "July 4, 2026",
    readTime: "10 min read",
    tags: ["加州租房", "租房清单", "租赁合同", "押金", "新移民住房"],
    excerpt: "帮助第一次在加州租房的新移民从预算、找房和申请，一直准备到签约、付款及入住检查。",
    body: [
      "适合人群：第一次在加州租公寓、房屋或房间的人，没有美国信用记录或租房历史的新移民，需要准备收入和身份材料的租客，以及不熟悉押金、租约和入住检查流程的人。",
      "准备清单：每月可承受租金预算，水电、网络、停车、交通和保险预算，身份证件，收入证明、工作证明或资金证明，银行流水或储蓄证明，推荐人或以前房东信息，信用报告或没有美国信用记录的解释，申请费预算，押金和首月租金，租约问题清单，以及入住检查表和照片备份空间。",
      "先确定完整住房预算。不要只计算房租，还要加入水电、燃气、网络、停车、洗衣、通勤和租客保险。确认地点和通勤需求时，要检查工作地点、学校、公共交通、停车条件和周边生活设施。",
      "准备租房申请包，把身份证明、收入资料、资金证明和推荐信息整理成可以安全提交的文件。看房时应核实房源和出租人，实地或通过可信的实时视频方式看房，并确认联系人是否有权出租该房产。",
      "询问所有入住费用，要求书面列出申请费、押金、首月租金、停车费、宠物费和其他费用。签约前仔细阅读租期、租金到期日、逾期费、维修责任、室友、访客、宠物、转租、提前退租和续租规则。",
      "付款应使用可追踪方式，并保留申请费、押金和租金收据。入住当天记录墙面、地板、电器、门窗、烟雾报警器和已有损坏，并保存带日期的照片或视频。",
      "常见错误包括只看月租、不计算停车和其他费用，没有看房或核实出租人就付款，签约前不阅读提前退租和续租条款，现金付款没有收据，没有拍摄入住时房屋状况，以及向普通房源联系人提交完整 SSN 和护照扫描件却没有确认其身份。",
      "官方提醒：对于大多数加州住宅租赁，房东收取的押金通常不得超过一个月租金；搬出后，房东一般需要在 21 天内退还押金余额并说明合法扣款。部分房产或房东可能适用例外，签约前应查看加州司法部门和法院的最新说明。",
    ],
  },
  {
    id: "category-health",
    title: "加州医疗保险基础指南",
    category: "Health",
    image: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1200&q=80",
    createdAt: "July 4, 2026",
    readTime: "10 min read",
    tags: ["加州医疗保险", "Covered California", "Medi-Cal", "新移民医疗", "健康保险"],
    excerpt: "帮助新移民了解雇主保险、Covered California、Medi-Cal 和自费医疗的基本区别及申请准备。",
    body: [
      "适合人群：刚搬到加州尚未取得医疗保险的人，不清楚自己是否应申请 Covered California 或 Medi-Cal 的人，需要为配偶和子女安排保险的家庭，以及第一次比较美国医疗保险计划的人。",
      "准备清单：家庭成员名单、出生日期和家庭关系、加州地址、SSN、非公民家庭成员的相关移民文件号码、雇主和收入信息、现有保险及终止日期、常用医生和医院名单、常用处方药名单、预计看医生和用药频率，以及可以承受的月保费和医疗支出预算。",
      "先检查雇主保险，询问何时可以加入、雇主承担多少费用、家属费用和生效日期。Covered California 是加州官方健康保险市场，可以比较计划并判断是否符合经济补助条件。",
      "了解 Medi-Cal。Medi-Cal 是加州的 Medicaid 项目，主要为符合收入和其他资格要求的居民提供免费或低费用医疗服务。不同家庭成员可能因年龄、收入、身份和其他条件得到不同结果。",
      "确认申请时间。Covered California 有年度开放申请期。搬到加州、失去原有保险、结婚、生育或取得符合要求的身份等事件可能触发特别申请期；多数情况需要在事件附近的规定期限内申请。",
      "比较总成本时，不要只看月保费，还要比较 deductible、copay、coinsurance 和年度 out-of-pocket maximum。检查常用医生、医院、心理健康服务、药房和处方药是否属于计划网络或目录。",
      "提交申请后保存申请编号，及时上传收入、住址、身份或生活事件证明。收到保险卡后建立账户、选择 PCP、设置自动付款，并了解紧急医疗、Urgent Care 和处方续配方式。",
      "官方提醒：移民身份、收入计算和医疗资格规则较复杂，而且联邦及加州政策可能变化。Covered California 说明，家庭可以通过申请系统查看成员是否可能符合 Covered California 或 Medi-Cal，但提交申请前应查看最新移民资格和政策更新。",
    ],
  },
  {
    id: "guide-1",
    title: "加州驾照申请步骤",
    category: "DMV",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAMKD1Df0ESEk-lv-uH3ZYYdkSP-bBXXV1gPf6iPpEzeo-WoSUru8NN6yalo1StqQBq2DT8mOaPEf0dYO45F_A2Xw7c7xmakcj4e_jVKteedu-R4wu_VB6GRNOOo9R4PspBiXST5fKNuZecFPMg8iaCVQL_l-Ebauyg0Twb-KhtkGr9E3LbASlvSDMCL59o_CecUKE05Kh94NJOHr4Lv3YyPJP2q25Qpz2cwmGBNwiplaTOhr_IXrIi5zQFvsHPOJC-uOtmHNwP53E",
    createdAt: "July 4, 2026",
    readTime: "10 min read",
    tags: ["加州驾照", "DMV", "笔试", "路考", "新移民"],
    excerpt: "帮助第一次申请加州驾照的新移民了解需要准备的材料、考试流程和 DMV 办理步骤。",
    body: [
      "适合人群：刚搬到加州需要合法开车的新居民、持有外国或其他州驾照的人、第一次申请美国驾照的成年人，以及需要了解普通驾照和 REAL ID 驾照区别的人。",
      "准备清单：护照及适用的合法身份或入境文件、加州居住地址证明、Social Security Number、外国或其他州驾照、眼镜或隐形眼镜、申请费付款方式、路考车辆、车辆注册、保险证明、加州驾驶手册和笔试练习材料。没有 SSN 时，应先确认自己适用的 DMV 要求。",
      "第一步是确定申请类型。根据自己的情况选择普通驾照、REAL ID 驾照或适用于特定申请人的 AB 60 驾照。AB 60 驾照不能作为 REAL ID 使用。",
      "在线填写 Driver's License or ID Card Application 后，仍需按要求到 DMV 办公室完成身份验证和后续程序。到现场时携带申请确认信息和文件原件，DMV 通常会核验文件、拍照、采集指纹并收取申请费。",
      "申请人需要完成视力检查和交通法规知识测试。考试前应阅读最新版 California Driver's Handbook，不要只依赖非官方模拟题。没有符合条件的现有驾照时，通常需要先取得 instruction permit，再按规定练习驾驶。",
      "预约路考前，确认车辆能安全驾驶，并具有有效注册和保险。提前熟悉转弯、停车、变道、观察路况和限速规则。通过后，DMV 通常会先提供临时驾照，正式驾照之后邮寄至登记地址。",
      "常见错误：没有先确认申请普通驾照、REAL ID 还是 AB 60，携带复印件但没有原件或认证文件，居住证明姓名或地址不一致，路考当天车辆没有有效保险或注册，把外国驾照自动视为可以免除加州考试，以及申请后搬家却没有及时更新邮寄地址。",
      "官方提醒：驾照要求会因年龄、身份文件和申请类型而不同。提交申请前应使用加州 DMV 官方文件清单，并查看最新版驾驶手册。不要仅依赖驾校、论坛或社交媒体信息。",
    ],
    officialLinks: [
      {
        title: "California DMV — Driver's Licenses",
        url: "https://www.dmv.ca.gov/portal/driver-licenses-identification-cards/driver-licenses-dl/",
        purpose: "查看加州驾照申请条件、主要材料和办理流程。",
      },
      {
        title: "DMV — Online Driver's License or ID Application",
        url: "https://www.dmv.ca.gov/portal/driver-licenses-identification-cards/dl-id-online-app-edl-44/",
        purpose: "在线填写驾照或身份证申请表。",
      },
      {
        title: "California Driver's Handbook",
        url: "https://www.dmv.ca.gov/portal/handbook/california-driver-handbook/",
        purpose: "学习笔试、交通法规和安全驾驶内容。",
      },
      {
        title: "DMV Driver's Handbooks in Different Languages",
        url: "https://www.dmv.ca.gov/portal/driver-handbooks/",
        purpose: "查找英文、中文、西班牙文等不同语言的驾驶手册。",
      },
      {
        title: "DMV Appointments",
        url: "https://www.dmv.ca.gov/portal/appointments/",
        purpose: "预约 DMV 办公室服务或路考。",
      },
      {
        title: "DMV Office Locations",
        url: "https://www.dmv.ca.gov/portal/locations/",
        purpose: "按照城市或邮政编码查找附近 DMV 办公室。",
      },
    ],
  },
  {
    id: "guide-real-id-documents",
    title: "REAL ID 材料准备指南",
    category: "DMV",
    image: "https://images.unsplash.com/photo-1554224154-22dec7ec8818?auto=format&fit=crop&w=1200&q=80",
    createdAt: "July 4, 2026",
    readTime: "8 min read",
    tags: ["REAL ID", "加州 DMV", "身份证明", "住址证明", "机场证件"],
    excerpt: "帮助申请人一次性整理 REAL ID 所需的身份证明、SSN、加州住址和姓名变更材料。",
    body: [
      "适合人群：准备第一次申请加州 REAL ID 的居民、计划把普通驾照或身份证升级为 REAL ID 的人、需要使用州证件搭乘受联邦规定约束的国内航班或进入特定联邦设施的人，以及持有符合条件移民身份文件的非美国公民。",
      "准备清单：一份 DMV 接受的身份证明原件或认证副本、两份显示加州实际居住地址的证明、SSN 或适用的例外证明、姓名变更文件、当前驾照或州身份证、DMV 在线申请确认信息，以及所有文件上的完整法定姓名和出生日期核对表。",
      "先确认自己是否需要 REAL ID。REAL ID 不是驾驶所必需的，普通驾照仍可以用于驾驶，但不能代替符合联邦用途要求的证件。",
      "使用 DMV 官方 Checklist，根据个人身份选择可以接受的文件。身份证明通常需要显示出生日期和完整法定姓名，例如符合要求的护照、出生证明、永久居民卡或其他 DMV 接受的身份文件。",
      "准备两份加州居住证明。两份文件通常都应显示申请人的姓名及同一个加州实际地址；可接受文件可能包括账单、银行记录、保险文件、租赁文件或就业文件。",
      "处理姓名不一致问题。身份文件、SSN 记录和住址文件上的姓名不一致时，准备连接各个姓名的正式变更文件，例如结婚证、离婚判决或法院命令。",
      "填写申请并前往 DMV。即使已经在线上传文件，也应携带要求的文件前往办公室。DMV 核实材料后完成照片、指纹及相关申请程序，并在收到正式证件前提供收据或临时文件。",
      "常见错误包括只准备一份住址证明、使用只有邮政信箱没有实际居住地址的文件、两份住址证明显示不同地址、姓名与申请表不一致、用普通复印件代替原件或认证副本、认为所有非美国公民都不能申请 REAL ID，或认为 AB 60 驾照可以直接升级为 REAL ID。",
      "官方提醒：申请 REAL ID 通常需要身份证明、SSN 信息以及两份加州住址证明；某些申请人可能适用例外。AB 60 驾照申请人不符合 REAL ID 资格。最终材料要求以 DMV REAL ID Checklist 为准。",
    ],
    officialLinks: [
      {
        title: "California DMV — Apply for REAL ID",
        url: "https://www.dmv.ca.gov/portal/driver-licenses-identification-cards/real-id/",
        purpose: "查看 REAL ID 办理入口和基本说明。",
      },
      {
        title: "DMV REAL ID Interactive Checklist",
        url: "https://www.dmv.ca.gov/portal/driver-licenses-identification-cards/real-id/real-id-checklist/",
        purpose: "根据个人情况生成需要携带的材料清单。",
      },
      {
        title: "DMV — What Is REAL ID?",
        url: "https://www.dmv.ca.gov/portal/driver-licenses-identification-cards/real-id/what-is-real-id/",
        purpose: "了解 REAL ID 与普通驾照或身份证的区别。",
      },
      {
        title: "REAL ID Information for Non-U.S. Citizens",
        url: "https://www.dmv.ca.gov/portal/driver-licenses-identification-cards/real-id/what-is-real-id/real-id-info-non-u-s-citizens/",
        purpose: "查看非美国公民可使用的身份和居住证明。",
      },
      {
        title: "DMV REAL ID Document List PDF",
        url: "https://www.dmv.ca.gov/portal/uploads/2020/06/List_of_Docs_REALID.pdf",
        purpose: "下载可打印的官方材料清单。",
      },
      {
        title: "DMV Appointments",
        url: "https://www.dmv.ca.gov/portal/appointments/",
        purpose: "预约前往 DMV 提交材料。",
      },
    ],
  },
  {
    id: "guide-2",
    title: "第一次在加州租房完整 checklist",
    category: "Housing",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuD-K9DsVJH-QkarCUZtSS1HPYFbl0Ai-apnPW9qURHeUaCcCZso4JfsJ4bsAZcTZ7riVxJkm74cEJClIZ1qj3sa-zpvRNzKeFSdA-XLxXu4GVX0wtWi9oEIS982mKpBSA6UMpLL824T0phfByQKM98zZ5fSqhTf--_hxj-1JJSMCtVPVFB3XZPLpy4vSmSPnVrs8PY9v-2BLTdDDuJjK-dLKI3QjxXv4WKK0B1kRN28MtagZRJ62LKWPJ95iL3ZHt-UsvGPsshPfK0",
    createdAt: "July 4, 2026",
    readTime: "10 min read",
    tags: ["加州租房", "租房清单", "租赁合同", "押金", "新移民住房"],
    excerpt: "帮助第一次在加州租房的新移民从预算、找房和申请，一直准备到签约、付款及入住检查。",
    body: [
      "完整住房预算应包含房租、水电、燃气、网络、停车、洗衣、通勤和租客保险。第一次租房时，先把每月可承受成本写清楚，再看房源是否真的适合长期居住。",
      "找房时检查工作地点、学校、公共交通、停车条件和周边生活设施。不要只看地图距离，最好测试高峰期通勤，并确认夜间或周末交通是否可行。",
      "申请前准备身份证明、收入资料、资金证明、推荐信息和没有美国信用记录的解释。提交材料时注意安全，不要在未确认出租人身份前发送完整 SSN 或护照扫描件。",
      "签约前要求书面列出所有费用，包括申请费、押金、首月租金、停车费和宠物费。租约需要重点查看提前退租、续租、维修责任、访客、宠物、转租和逾期费条款。",
      "入住当天完成检查，拍摄墙面、地板、电器、门窗、烟雾报警器和已有损坏。保存签字租约、入住检查表、付款记录、维修申请和与房东的书面沟通。",
      "官方提醒：押金和扣款规则会受到加州法律和具体租赁情况影响。对于大多数住宅租赁，搬出后房东一般需要在 21 天内退还押金余额并说明合法扣款。",
    ],
  },
  {
    id: "guide-rental-scams",
    title: "加州租房常见骗局和避坑",
    category: "Housing",
    image: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?auto=format&fit=crop&w=1200&q=80",
    createdAt: "July 4, 2026",
    readTime: "8 min read",
    tags: ["租房骗局", "假房东", "加州租房", "押金诈骗", "租房避坑"],
    excerpt: "帮助租客识别假房源、冒充房东、虚假中介和要求提前转账等常见租房骗局。",
    body: [
      "适合人群：通过分类广告、社交媒体或租房网站找房的人，尚未到达加州需要远程租房的新移民，不熟悉当地租金水平和付款方式的人，以及因急于入住而容易忽略核验步骤的人。",
      "准备清单：房源完整地址、房东或物业公司姓名、经纪人执照信息、多个平台价格对比、看房预约、租约副本、费用明细、房产或管理方联系方式、付款收据、骗局报告和银行紧急联系方式。",
      "先检查价格是否异常。明显低于同一地区类似房源的价格需要提高警惕。搜索同一地址，查看该地址是否同时出现在出售和出租网站，以及联系人和价格是否一致。",
      "核实联系人身份，不要只依据社交媒体头像、电子邮件签名或发来的证件照片判断身份。实地或实时视频看房，预先录制的视频不能证明联系人目前有权出租房屋。",
      "阅读完整租约，租约应写明地址、租金、押金、租期、双方姓名和付款方式。拒绝异常付款要求，例如立即电汇、购买礼品卡、发送加密货币或向陌生第三方付款。",
      "保存广告截图、电子邮件、电话号码、付款指示和收据。发现问题后立即联系银行或支付平台尝试阻止交易，并向相关执法、消费者保护或房地产监管机构报告。",
      "常见错误包括因为对方发送身份证照片就相信其身份，相信“房东在国外，钥匙之后邮寄”的说法，未看房就支付申请费或押金，把验证码和银行密码发给房东，只通过即时通信软件沟通且没有正式租约，以及在“还有很多申请人”的压力下立即付款。",
      "官方提醒：加州房地产管理部门持续警告，骗子会复制真实房源制造假房源、冒充持牌经纪人或物业管理人员，并诱导租客提前电子转账。2026 年的官方警示也特别提到冒充房地产专业人士的社交媒体和分类广告账户。",
    ],
  },
  {
    id: "forum-first-30-days",
    title: "First 30 Days in California Community Guide",
    category: "Community Guide",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    createdAt: "July 2, 2026",
    readTime: "9 min read",
    tags: ["First 30 Days", "Newcomer", "Documents", "Community"],
    excerpt: "A week-by-week outline for documents, housing, transportation, banking, health, and local setup.",
    body: [
      "In week one, focus on stable contact information: a local phone number, email access, temporary or permanent address, important document scans, and a simple folder for receipts and appointment confirmations.",
      "In weeks one and two, handle essentials such as housing, utilities, banking, transportation planning, and health coverage research. If you need a DMV, SSN, school, or benefits appointment, check official websites early because appointment availability can vary.",
      "By week three, build local routines: grocery options, pharmacy, primary care search, commute routes, school or work onboarding, and emergency contacts. Save addresses and phone numbers for nearby clinics, transit services, and city resources.",
      "By week four, review what is still pending and ask the community targeted questions. Good forum posts include your city, timeline, documents already prepared, and what decision you are trying to make.",
    ],
  },
  {
    id: "trending-ssn",
    title: "SSN Appointment Wait Times in San Jose",
    category: "Forum Question",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    createdAt: "July 2, 2026",
    readTime: "4 min read",
    tags: ["SSN", "Appointments", "San Jose", "Documents"],
    excerpt: "Understand how to prepare for an SSN visit and what to do when appointments are limited.",
    body: [
      "Appointment availability can change quickly, so check the Social Security Administration website and local office guidance before making plans. Users in San Jose may also compare nearby offices if travel is realistic.",
      "Prepare identity, immigration, work authorization, school, or employment documents based on your situation. Bring originals when required and keep copies for your own records.",
      "If appointments are limited, ask the office about walk-in rules, rescheduling options, and whether another nearby office can help. Avoid relying only on community reports because policies and wait times can change.",
      "After the appointment, keep receipts or confirmation notes and monitor mail delivery. If the card does not arrive within the expected window, contact SSA directly for next steps.",
    ],
  },
  {
    id: "trending-banking",
    title: "没有 SSN 可以做哪些银行准备",
    category: "Forum Question",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80",
    createdAt: "July 4, 2026",
    readTime: "6 min read",
    tags: ["没有 SSN", "ITIN", "银行开户", "护照", "新移民金融"],
    excerpt: "帮助暂时没有 Social Security Number 的新移民准备替代证件、比较银行政策并安全安排日常财务。",
    body: [
      "适合人群：尚未获得 SSN 的新移民、不符合 SSN 申请资格但准备申请 ITIN 的人、需要接收资金或支付账单的人，以及被一家银行拒绝后不知道下一步怎么办的人。",
      "准备清单：有效护照、第二份政府签发证件、ITIN 文件、美国地址证明、电话号码、电子邮箱、签证、I-94 或其他身份文件、初始存款、接受非 SSN 客户的金融机构名单，以及各银行文件费用和开户方式比较表。",
      "先了解 SSN 与 ITIN 的区别。ITIN 是税务识别号码，不等于工作许可，也不能代替所有要求 SSN 的服务。只有符合 IRS 规定并具有联邦税务用途的人才应申请 ITIN。",
      "联系多家银行或信用合作社，明确询问：没有 SSN 是否可以开户？是否接受 ITIN、外国护照或其他政府证件？除护照外，准备地址、联系方式和银行可能要求的第二份证件。",
      "询问可以开设的账户类型。某些机构可能对没有 SSN 的客户提供不同账户、申请渠道或功能限制。优先比较低费用账户，包括月费、最低余额、ATM 网络、国际汇款和透支政策。",
      "建立文件记录，保存银行人员姓名、沟通日期、要求的材料及申请结果。以后获得 SSN 或 ITIN 时，询问银行是否需要更新客户资料。",
      "常见错误包括认为没有 SSN 就一定不能开任何银行账户、认为所有银行都必须接受外国护照、为了开户提交虚假 SSN、向收费中介购买所谓的 SSN、把 ITIN 误认为工作许可，以及长期使用他人银行账户收工资或存放个人资金。",
      "官方提醒：CFPB 明确说明，没有 SSN 并不一定代表不能取得银行或信用合作社账户，但金融机构仍需核验身份，而且各机构政策不同。申请人必须如实提供信息，不得使用虚假或他人的号码。",
    ],
    officialLinks: [
      {
        title: "CFPB — Bank Accounts and Services",
        url: "https://www.consumerfinance.gov/consumer-tools/bank-accounts/",
        purpose: "查看没有 SSN 时的银行账户基本权利和准备方式。",
      },
      {
        title: "FDIC GetBanked",
        url: "https://www.fdic.gov/getbanked",
        purpose: "查看银行可能接受的外国护照、领事身份证或 ITIN 等材料。",
      },
      {
        title: "IRS — Individual Taxpayer Identification Number",
        url: "https://www.irs.gov/tin/itin/individual-taxpayer-identification-number-itin",
        purpose: "了解 ITIN 的用途、资格和限制。",
      },
      {
        title: "IRS — How to Apply for an ITIN",
        url: "https://www.irs.gov/tin/itin/how-to-apply-for-an-itin",
        purpose: "查看 Form W-7、证明文件和申请方式。",
      },
      {
        title: "IRS Form W-7",
        url: "https://www.irs.gov/forms-pubs/about-form-w-7",
        purpose: "下载或查看 ITIN 申请表及说明。",
      },
      {
        title: "FDIC BankFind Suite",
        url: "https://banks.data.fdic.gov/bankfind-suite/bankfind",
        purpose: "核实准备开户的银行是否受 FDIC 保障。",
      },
    ],
  },
  {
    id: "guide-first-doctor-visit",
    title: "第一次在美国看医生流程",
    category: "Health",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1200&q=80",
    createdAt: "July 4, 2026",
    readTime: "9 min read",
    tags: ["美国看医生", "家庭医生", "医疗预约", "保险网络", "医疗账单"],
    excerpt: "帮助第一次在美国就医的新移民完成找医生、预约、就诊、检查、处方和账单处理。",
    body: [
      "适合人群：第一次使用美国医疗保险的人，不熟悉 PCP、专科转诊和网络内医生的人，英语沟通有困难需要翻译支持的人，以及需要为自己或家人安排常规就诊的人。",
      "准备清单：保险卡或 Medi-Cal Benefits Identification Card、照片证件、PCP 姓名和诊所地址、症状出现时间、目前使用的药物和剂量、过敏记录、既往病史和疫苗记录、海外检查报告、希望咨询的问题、首选语言及口译需求、copay 付款方式。",
      "先判断就医类型。常规体检、慢性病和一般症状通常先联系 PCP。紧急或危及生命的情况应立即使用当地紧急医疗服务。",
      "寻找网络内医生时，使用保险公司或 Medi-Cal 计划的官方医生目录，并打电话确认医生仍接受该保险及新患者。Medi-Cal 将 PCP 定义为生病或体检时通常前往的医生或诊所。",
      "预约时提供姓名、出生日期、保险信息、主要症状和语言需求，并询问是否需要提前填写表格。确认 copay，以及看专科、做影像或化验是否需要 PCP 转诊或保险授权。",
      "第一次就诊通常需要填写病史、隐私和财务责任表格。就诊时主动提出问题，并确认自己理解治疗方案。之后要确认在哪里做检查、如何查看结果、药物如何服用，以及出现副作用时联系谁。",
      "查看保险解释和医疗账单。Explanation of Benefits 通常不是账单；收到正式账单后，应与保险记录核对。把复诊日期、检查结果和用药变化记录在个人医疗档案中。",
      "常见错误包括只在网上看到医生名字就假设其仍属于保险网络，没有询问是否接受新患者，忘记说明中药、保健品或海外处方药，不理解治疗方案却不提问，把 Explanation of Benefits 当成必须立即支付的账单，没有查看检查结果或完成转诊，以及因语言困难让未成年子女承担复杂医疗翻译。",
      "官方提醒：医疗网络、转诊和费用取决于个人保险计划。Medi-Cal 管理式医疗成员通常应先联系计划内 PCP，紧急情况除外。本文不能代替医生诊断；出现紧急或危及生命的情况，应立即拨打 911 或前往急诊。",
    ],
  },
  {
    id: "guide-legal-30-day-documents",
    title: "到加州前 30 天文件整理计划",
    category: "Legal",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80",
    createdAt: "July 4, 2026",
    readTime: "9 min read",
    tags: ["移民文件", "入境准备", "I-94", "文件整理", "搬到加州"],
    excerpt: "帮助新移民在出发前整理身份、入境、家庭、医疗、教育和财务文件，并建立安全备份。",
    body: [
      "适合人群：未来 30 天内搬到加州的人、携带配偶或子女一起入境的家庭，以及需要办理驾照、学校、银行、住房和医疗事务的新居民。",
      "准备清单：护照和签证、移民签证包或批准通知、I-20、DS-2019、EAD、绿卡或其他身份文件、出生证、结婚证、离婚文件、子女监护文件、驾照和驾驶记录、疫苗和医疗记录、学历和职业资格文件、工作合同、银行及资金证明、保险文件、加州地址、紧急联系人、纸质副本、加密电子副本和文件清单。",
      "第一步是建立文件总目录。建议按身份、家庭、医疗、教育、工作、银行、住房和交通分类，并为每位家庭成员建立独立文件夹。重要原件应放入随身行李，不要放在托运行李中。",
      "出发前核对姓名、出生日期和英文拼写。护照、签证、出生证、学校记录和银行文件如果存在拼写差异，应记录差异来源，并提前询问学校、法院、医疗机构或其他机构是否需要认证翻译。",
      "入境后，适用的非移民旅客可以从 CBP 系统获取最近一次电子 I-94，并核对姓名、身份类别和允许停留日期。搬家后不要只在邮局转寄邮件，许多非公民还需要根据 USCIS 要求更新地址；当前 USCIS 说明通常为搬家后 10 天内。",
      "常见错误包括把所有原件放进托运行李、只有手机照片没有安全备份、忘记保存移民申请和批准文件、入境后不核对 I-94、搬家后没有检查 USCIS 地址更新要求，以及把 SSN、护照和银行文件存入无密码共享网盘。",
      "官方提醒：本清单是文件整理工具，不是移民法律意见。不同签证、身份和申请案件有不同要求，应通过 CBP 核对 I-94，并通过 USCIS 官方页面确认自己的地址申报义务。",
    ],
  },
  {
    id: "guide-newcomer-job-search",
    title: "新移民找工作准备清单",
    category: "Jobs",
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80",
    createdAt: "July 4, 2026",
    readTime: "10 min read",
    tags: ["新移民找工作", "美式简历", "工作许可", "I-9", "加州就业"],
    excerpt: "帮助新移民确认工作资格，准备美式简历、就业文件、推荐人和安全求职计划。",
    body: [
      "适合人群：准备在加州寻找第一份工作的新移民、有海外学历和工作经验的人、不熟悉美国简历和面试流程的人，以及需要确认工作授权和 I-9 文件的人。",
      "准备清单：有效工作授权证明、USCIS I-9 可接受文件清单、一页或两页英文简历、不同岗位的简历版本、LinkedIn 或其他专业档案、海外学历和资格证书、学历评估或执照认证资料、推荐人、英文自我介绍、专业邮箱、语音信箱、求职申请记录表、面试交通和服装安排。",
      "先确认是否获得工作授权。签证、身份文件和工作许可规则不同，不要仅凭 SSN 判断自己是否可以工作。获聘后，雇主使用 Form I-9 核验身份和就业资格；雇主不应自行要求员工必须提交某一种特定文件。",
      "制作美式简历时，突出技能、成果和与职位相关的经验。一般不放照片、年龄、婚姻状况、护照号码或 SSN。针对不同职位调整关键词和经历顺序，不要所有岗位使用同一份材料。",
      "处理海外学历和资格时，先确认目标职业是否要求学历评估、州执照、背景调查或考试。求职渠道可以包括公司官网、可靠招聘平台、CalJOBS、行业协会、学校资源和社区就业资源。",
      "可以联系 AJCC，America's Job Center of California 提供免费的就业和培训服务，可帮助寻找岗位、改善简历和了解培训项目。面试前练习介绍自己、解释海外经验、说明成果，并准备岗位相关问题。",
      "常见错误包括把取得 SSN 等同于取得工作授权、在简历中写入 SSN 或护照号码、没有核实受监管职业执照要求、为保证录用向招聘人员付款、允许雇主强制指定 I-9 文件，以及没有保留 offer 和工资条件的书面记录。",
      "官方提醒：工作授权问题应根据个人身份文件向 USCIS、合格移民律师或受认可的法律服务机构确认。加州 EDD 和 AJCC 可以提供就业信息，但不能替代个人移民法律意见。",
    ],
  },
  {
    id: "guide-school-esl-resources",
    title: "小孩入学和 ESL 资源指南",
    category: "Education",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80",
    createdAt: "July 4, 2026",
    readTime: "9 min read",
    tags: ["加州入学", "ESL", "English Learner", "新移民学生", "学区"],
    excerpt: "帮助新移民家长找到所属学区、准备入学文件，并了解英语学习和 newcomer 学生支持资源。",
    body: [
      "适合人群：带学龄儿童搬到加州的新移民家庭、子女曾在其他国家或美国其他州上学的家长、子女需要英语语言支持的家庭，以及不熟悉学区和入学流程的家长。",
      "准备清单：加州居住地址、孩子出生日期和年龄证明、家长或监护人身份证明、住址证明、疫苗和医疗记录、以前学校成绩单和在读证明、中学生课程名称及学分记录、特殊教育计划或医疗安排、监护权文件、翻译件、家庭主要语言、口译需求和紧急联系人。",
      "第一步是根据实际居住地址找到所属 school district，并联系学区 enrollment office。不同学区接受的住址、年龄和监护证明可能不同，应要求学校提供正式入学清单。",
      "提交以前的学习记录时，中学生应尽量提供详细课程说明、学分记录和毕业要求信息，减少学分判断困难。海外疫苗记录应尽量包含疫苗名称和接种日期。",
      "学校可能通过家庭语言调查和英语能力评估判断学生是否需要 English Learner 服务。家长可以询问学校提供的是课堂内支持、指定英语语言发展课程、双语项目还是 newcomer program。",
      "ESL 不是一所独立学校，而是学校可能提供的语言支持。家长也可以询问学校是否提供翻译文件和会议口译，不应让孩子承担复杂的学校行政翻译。",
      "常见错误包括尚未确定实际住址就默认孩子属于某所学校、等所有海外文件完成正式翻译后才联系学区、只提交总成绩没有课程明细、因孩子日常英语不错就忽略学术英语评估，以及没有提供特殊教育或医疗支持记录。",
      "官方提醒：入学材料和分校规则由当地学区执行。加州教育厅提供 newcomer students 和 English Learner 家长资源，家长应先联系所属学区，再使用州级资源了解可获得的支持。",
    ],
  },
  {
    id: "guide-california-transportation",
    title: "加州通勤、买车和保险基础",
    category: "Transportation",
    image: "https://images.unsplash.com/photo-1494515843206-f3117d3f51b7?auto=format&fit=crop&w=1200&q=80",
    createdAt: "July 4, 2026",
    readTime: "11 min read",
    tags: ["加州通勤", "加州买车", "汽车保险", "车辆注册", "新移民交通"],
    excerpt: "帮助新移民比较公共交通与买车成本，并了解车辆购买、注册和汽车保险的基本要求。",
    body: [
      "适合人群：正在决定是否需要买车的新移民、需要规划工作或学校通勤的人、第一次在美国购买新车或二手车的人、从其他州或国家带车进入加州的人，以及不熟悉汽车保险和 DMV 注册的人。",
      "准备清单：家庭和工作地点的通勤地图、公交地铁和通勤铁路费用、驾照或学习许可证情况、买车总预算、贷款利率和首付款预算、车辆历史报告、独立机械检查、title 和 VIN、保险报价、注册税费、停车维修预算、卖家身份信息、签署文件和付款记录。",
      "先测试不买车的通勤方案。比较公交、铁路、骑车、步行、公司班车和拼车，计算时间、换乘和晚间服务。加州不同城市差异很大，具体路线比城市平均印象更重要。",
      "计算真实养车成本。除车价或月供外，还要包括销售税、注册、贷款利息、汽车保险、燃油或充电、停车、保养和维修。在决定购买哪辆车之前，最好使用 VIN 或具体车型取得保险报价。",
      "购买二手车时，检查 title、事故或报废记录，并考虑安排独立机械师检查。区分经销商和私人交易：加州 Car Buyer's Bill of Rights 的部分保护适用于持牌经销商零售交易，但不适用于私人之间的车辆交易。",
      "完成产权和注册手续。私人购买通常需要 title、里程信息、适用的 smog certification、费用和使用税。买方通常应在购买后 10 天内完成产权转移要求。新居民把外州或外国注册车辆带入加州时，通常需要在成为居民或把车辆带入州内后的 20 天内办理注册。",
      "常见错误包括只看车辆月供、不计算保险和停车、买车后才询问保险价格、私人交易时没有核对 title 和卖家身份、没有进行独立机械检查、把经销商附加产品误认为法律强制购买、外州车辆超过规定时间仍未注册，以及使用不符合加州要求的外州保险。",
      "官方提醒：加州要求在州内道路上驾驶或停放的车辆维持保险或其他被认可的财务责任证明。标准汽车责任险最低额度目前为每人身体伤害或死亡 30,000 美元、每次事故合计 60,000 美元及每次事故财产损失 15,000 美元。最低额度不一定适合每个家庭，应向持牌保险公司或经纪人确认保障。",
    ],
  },
];

export function getBlogArticle(id: string) {
  return BLOG_ARTICLES.find((article) => article.id === id);
}
